SCHEMAS = {'vertical_bull_put': {'source_example': 'catalog/references/bull-put-spread-option-screener-vertical-bull-put-etf-08-30-2025.csv',
                       'footer_timestamp': None,
                       'row_count': 411,
                       'columns': ['Symbol',
                                   'Price~',
                                   'Exp Date',
                                   'DTE',
                                   'Leg1 Strike',
                                   'Type',
                                   'Bid1',
                                   'Leg2 Strike',
                                   'Type',
                                   'Ask2',
                                   'BE',
                                   'BE%',
                                   'Max Profit',
                                   'Max Loss',
                                   'Max Profit%',
                                   'Risk/Reward',
                                   'IV Rank',
                                   'Loss Prob']}}
