SCHEMAS = {'vertical_bull_put': {'source_example': 'catalog/references/bull-put-spread-option-screener-vertical-bull-put-etf-08-30-2025.csv',
                       'footer_timestamp': '08-30-2025 05:23pm CDT',
                       'columns': ['Symbol',
                                   'Price~',
                                   'Exp Date',
                                   'DTE',
                                   'Leg1 Strike',
                                   'Type',
                                   'Bid1',
                                   'Leg2 Strike',
                                   'Type',
                                   'Ask2',
                                   'BE',
                                   'BE%',
                                   'Max Profit',
                                   'Max Loss',
                                   'Max Profit%',
                                   'Risk/Reward',
                                   'IV Rank',
                                   'Loss Prob'],
                       'sample_row': ['GLD',
                                      '318.07',
                                      '2025-10-17',
                                      '48',
                                      '315.00',
                                      'Put',
                                      '5.35',
                                      '287.00',
                                      'Put',
                                      '0.38',
                                      '310.03',
                                      '-2.53%',
                                      '4.97',
                                      '23.03',
                                      '+21.58%',
                                      '4.63 to 1',
                                      '21.97%',
                                      '33.3%']},
 'vertical_bull_call': {'source_example': 'catalog/references/bull-call-spread-option-screener-vertical-bull-call-etf-08-30-2025.csv',
                        'footer_timestamp': '08-30-2025 08:01pm CDT',
                        'columns': ['Symbol',
                                    'Price~',
                                    'Exp Date',
                                    'DTE',
                                    'Leg1 Strike',
                                    'Type',
                                    'Ask1',
                                    'Leg2 Strike',
                                    'Type',
                                    'Bid2',
                                    'BE',
                                    'BE%',
                                    'Max Profit',
                                    'Max Loss',
                                    'Max Profit%',
                                    'Risk/Reward',
                                    'IV Rank',
                                    'Profit Prob'],
                        'sample_row': ['GLD',
                                       '318.07',
                                       '2025-09-19',
                                       '20',
                                       '305.00',
                                       'Call',
                                       '14.45',
                                       '318.00',
                                       'Call',
                                       '4.95',
                                       '314.5',
                                       '-1.12%',
                                       '3.5',
                                       '9.5',
                                       '+36.84%',
                                       '2.71 to 1',
                                       '21.97%',
                                       '61.1%']},
 'covered_call_main': {'source_example': 'catalog/references/covered-call-option-screener-call-short-stock-08-30-2025.csv',
                       'footer_timestamp': '08-30-2025 08:22pm CDT',
                       'columns': ['Symbol',
                                   'Price~',
                                   'Exp Date',
                                   'DTE',
                                   'Strike',
                                   'Type',
                                   'Moneyness',
                                   'Bid',
                                   'BE (Bid)',
                                   '%BE (Bid)',
                                   'Volume',
                                   'Open Int',
                                   'IV Rank',
                                   'Delta',
                                   'Return',
                                   'Ann Rtn',
                                   'Ptnl Rtn',
                                   'Profit Prob'],
                       'sample_row': ['AAPL',
                                      '232.14',
                                      '2025-09-26',
                                      '27',
                                      '235.00',
                                      'Call',
                                      '-1.23%',
                                      '4.65',
                                      '227.49',
                                      '-2.00%',
                                      '1121',
                                      '2405',
                                      '15.42%',
                                      '-0.451519',
                                      '2.0%',
                                      '27.6%',
                                      '3.3%',
                                      '62.9%']},
 'covered_call_custom': {'source_example': 'catalog/references/covered-call-option-screener-call-short-stock-08-30-2025 '
                                           '(1).csv',
                         'footer_timestamp': '08-30-2025 08:23pm CDT',
                         'columns': ['Symbol',
                                     '%Chg~',
                                     'Volume~',
                                     'Price~',
                                     'Exp Date',
                                     'DTE',
                                     'Strike',
                                     'Type',
                                     'Moneyness',
                                     'Bid',
                                     'Ask',
                                     'Mid',
                                     'Volume',
                                     'Open Int',
                                     'IV Rank',
                                     'Delta',
                                     'Theta',
                                     'BE (Ask)',
                                     '%BE (Ask)',
                                     'ITM Prob',
                                     'TP Ask',
                                     '%TP Ask(a)',
                                     'Static Ann Rtn',
                                     'Ann Yield to Strike%',
                                     'Exp B4 Earnings'],
                         'sample_row': ['CRM',
                                        '+0.68%',
                                        '7363200',
                                        '256.25',
                                        '2025-09-19',
                                        '20',
                                        '255.00',
                                        'Call',
                                        '+0.49%',
                                        '12.7',
                                        '12.95',
                                        '12.83',
                                        '440',
                                        '498',
                                        '62.40%',
                                        '-0.546596',
                                        '0.30795',
                                        '243.3',
                                        '-5.05%',
                                        '51.68%',
                                        '11.7',
                                        '83.33%',
                                        '90.45%',
                                        '90.89%',
                                        'No']}}
