SCHEMAS = {'vertical_bull_put': {'source_example': 'catalog/references/bull-put-spread-option-screener-vertical-bull-put-etf-08-30-2025.csv',
                       'footer_timestamp': '08-30-2025 05:23pm CDT',
                       'columns': ['Symbol',
                                   'Price~',
                                   'Exp Date',
                                   'DTE',
                                   'Leg1 Strike',
                                   'Type',
                                   'Bid1',
                                   'Leg2 Strike',
                                   'Type',
                                   'Ask2',
                                   'BE',
                                   'BE%',
                                   'Max Profit',
                                   'Max Loss',
                                   'Max Profit%',
                                   'Risk/Reward',
                                   'IV Rank',
                                   'Loss Prob'],
                       'sample_row': ['GLD',
                                      '318.07',
                                      '2025-10-17',
                                      '48',
                                      '315.00',
                                      'Put',
                                      '5.35',
                                      '287.00',
                                      'Put',
                                      '0.38',
                                      '310.03',
                                      '-2.53%',
                                      '4.97',
                                      '23.03',
                                      '+21.58%',
                                      '4.63 to 1',
                                      '21.97%',
                                      '33.3%']},
 'vertical_bull_call': {'source_example': 'catalog/references/bull-call-spread-option-screener-vertical-bull-call-etf-08-30-2025.csv',
                        'footer_timestamp': '08-30-2025 08:01pm CDT',
                        'columns': ['Symbol',
                                    'Price~',
                                    'Exp Date',
                                    'DTE',
                                    'Leg1 Strike',
                                    'Type',
                                    'Ask1',
                                    'Leg2 Strike',
                                    'Type',
                                    'Bid2',
                                    'BE',
                                    'BE%',
                                    'Max Profit',
                                    'Max Loss',
                                    'Max Profit%',
                                    'Risk/Reward',
                                    'IV Rank',
                                    'Profit Prob'],
                        'sample_row': ['GLD',
                                       '318.07',
                                       '2025-09-19',
                                       '20',
                                       '305.00',
                                       'Call',
                                       '14.45',
                                       '318.00',
                                       'Call',
                                       '4.95',
                                       '314.5',
                                       '-1.12%',
                                       '3.5',
                                       '9.5',
                                       '+36.84%',
                                       '2.71 to 1',
                                       '21.97%',
                                       '61.1%']},
 'covered_call_main': {'source_example': 'catalog/references/covered-call-option-screener-call-short-stock-08-30-2025.csv',
                       'footer_timestamp': '08-30-2025 08:22pm CDT',
                       'columns': ['Symbol',
                                   'Price~',
                                   'Exp Date',
                                   'DTE',
                                   'Strike',
                                   'Type',
                                   'Moneyness',
                                   'Bid',
                                   'BE (Bid)',
                                   '%BE (Bid)',
                                   'Volume',
                                   'Open Int',
                                   'IV Rank',
                                   'Delta',
                                   'Return',
                                   'Ann Rtn',
                                   'Ptnl Rtn',
                                   'Profit Prob'],
                       'sample_row': ['AAPL',
                                      '232.14',
                                      '2025-09-26',
                                      '27',
                                      '235.00',
                                      'Call',
                                      '-1.23%',
                                      '4.65',
                                      '227.49',
                                      '-2.00%',
                                      '1121',
                                      '2405',
                                      '15.42%',
                                      '-0.451519',
                                      '2.0%',
                                      '27.6%',
                                      '3.3%',
                                      '62.9%']},
 'covered_call_custom': {'source_example': 'catalog/references/covered-call-option-screener-call-short-stock-08-30-2025 '
                                           '(1).csv',
                         'footer_timestamp': '08-30-2025 08:23pm CDT',
                         'columns': ['Symbol',
                                     '%Chg~',
                                     'Volume~',
                                     'Price~',
                                     'Exp Date',
                                     'DTE',
                                     'Strike',
                                     'Type',
                                     'Moneyness',
                                     'Bid',
                                     'Ask',
                                     'Mid',
                                     'Volume',
                                     'Open Int',
                                     'IV Rank',
                                     'Delta',
                                     'Theta',
                                     'BE (Ask)',
                                     '%BE (Ask)',
                                     'ITM Prob',
                                     'TP Ask',
                                     '%TP Ask(a)',
                                     'Static Ann Rtn',
                                     'Ann Yield to Strike%',
                                     'Exp B4 Earnings'],
                         'sample_row': ['CRM',
                                        '+0.68%',
                                        '7363200',
                                        '256.25',
                                        '2025-09-19',
                                        '20',
                                        '255.00',
                                        'Call',
                                        '+0.49%',
                                        '12.7',
                                        '12.95',
                                        '12.83',
                                        '440',
                                        '498',
                                        '62.40%',
                                        '-0.546596',
                                        '0.30795',
                                        '243.3',
                                        '-5.05%',
                                        '51.68%',
                                        '11.7',
                                        '83.33%',
                                        '90.45%',
                                        '90.89%',
                                        'No'],
                         'header_map': {'Symbol': 'symbol',
                                        '%Chg~': 'Percent Change',
                                        'Volume~': 'Volume',
                                        'Price~': 'Last',
                                        'Exp Date': 'Expiration Date',
                                        'DTE': 'DTE',
                                        'Strike': 'Strike Price',
                                        'Type': 'Option Type',
                                        'Moneyness': 'Moneyness',
                                        'Bid': 'Option Bid Price',
                                        'Ask': 'Option Ask Price',
                                        'Mid': 'Option Midpoint',
                                        'Volume': 'Option Volume',
                                        'Open Int': 'Option Open Interest',
                                        'IV Rank': 'IV Rank',
                                        'Delta': 'Delta',
                                        'Theta': 'Theta',
                                        'BE (Ask)': 'Break Even (Ask)',
                                        '%BE (Ask)': '% to Break Even (Ask)',
                                        'ITM Prob': 'ITM Probability',
                                        'TP Ask': 'Time Premium Ask',
                                        '%TP Ask(a)': '%Time Premium Ask '
                                                      'Annual Rtn%',
                                        'Static Ann Rtn': 'Static Annual '
                                                          'Return%',
                                        'Ann Yield to Strike%': 'Yield to '
                                                                'Strike Annual '
                                                                'Rtn%',
                                        'Exp B4 Earnings': 'Option Expires '
                                                           'Before Earnings'},
                         'logical_columns': ['symbol',
                                             'Percent Change',
                                             'Volume',
                                             'Last',
                                             'Expiration Date',
                                             'DTE',
                                             'Strike Price',
                                             'Option Type',
                                             'Moneyness',
                                             'Option Bid Price',
                                             'Option Ask Price',
                                             'Option Midpoint',
                                             'Option Volume',
                                             'Option Open Interest',
                                             'IV Rank',
                                             'Delta',
                                             'Theta',
                                             'Break Even (Ask)',
                                             '% to Break Even (Ask)',
                                             'ITM Probability',
                                             'Time Premium Ask',
                                             '%Time Premium Ask Annual Rtn%',
                                             'Static Annual Return%',
                                             'Yield to Strike Annual Rtn%',
                                             'Option Expires Before Earnings']},
 'csp_main': {'source_example': 'catalog/references/naked-put-option-screener-csp-stock-etf-08-30-2025.csv',
              'footer_timestamp': '08-30-2025 08:36pm CDT',
              'columns': ['Symbol',
                          'Price~',
                          'Exp Date',
                          'DTE',
                          'Strike',
                          'Type',
                          'Moneyness',
                          'Bid',
                          'BE (Bid)',
                          '%BE (Bid)',
                          'Volume',
                          'Open Int',
                          'IV Rank',
                          'Delta',
                          'Return',
                          'Ann Rtn',
                          'Profit Prob'],
              'sample_row': ['AAPL',
                             '232.14',
                             '2025-09-26',
                             '27',
                             '220.00',
                             'Put',
                             '-5.23%',
                             '1.97',
                             '218.03',
                             '-6.08%',
                             '301',
                             '1151',
                             '15.42%',
                             '0.207624',
                             '0.9%',
                             '12.2%',
                             '80.73%']},
 'csp_custom': {'source_example': 'catalog/references/naked-put-option-screener-csp-stock-etf-08-30-2025 '
                                  '(1).csv',
                'footer_timestamp': '08-30-2025 08:36pm CDT',
                'columns': ['Symbol',
                            'Ask',
                            'Bid',
                            '%Chg~',
                            'Volume~',
                            'Exp Date',
                            'DTE',
                            'Strike',
                            'Type',
                            'Moneyness',
                            'Ask',
                            'Last',
                            'Volume',
                            'Total OI',
                            'IV Rank',
                            'Delta',
                            'Theta',
                            'Vega',
                            'BE (Ask)',
                            '%BE (Ask)',
                            'Yield to Strike%',
                            'Ann Yield to Strike%',
                            'ITM Prob',
                            'OTM Prob',
                            'Short Term~'],
                'sample_row': ['AVGO',
                               '0',
                               '0',
                               '-3.65%',
                               '21610602',
                               '2025-09-19',
                               '20',
                               '280.00',
                               'Put',
                               '-5.85%',
                               '7.05',
                               '7.29',
                               '993',
                               '1899054',
                               '29.80%',
                               '0.286118',
                               '0.303205',
                               '-0.236709',
                               '272.95',
                               '-8.22%',
                               '2.46%',
                               '44.97%',
                               '31.23%',
                               '68.77%',
                               'Buy'],
                'header_map': {'Symbol': 'Symbol',
                               'Ask': 'Option Ask Price',
                               'Bid': 'Bid Price',
                               '%Chg~': 'Percent Change',
                               'Volume~': 'Volume',
                               'Exp Date': 'Expiration Date',
                               'DTE': 'DTE',
                               'Strike': 'Strike Price',
                               'Type': 'Option Type',
                               'Moneyness': 'Moneyness',
                               'Last': 'Option Last Price',
                               'Volume': 'Option Volume',
                               'Total OI': 'Total Options Open Interest',
                               'IV Rank': 'IV Rank',
                               'Delta': 'Delta',
                               'Theta': 'Theta',
                               'Vega': 'Vega',
                               'BE (Ask)': 'Break Even (Ask)',
                               '%BE (Ask)': '% to Break Even (Ask)',
                               'Yield to Strike%': 'Yield to Strike%',
                               'Ann Yield to Strike%': 'Yield to Strike Annual '
                                                       'Rtn%',
                               'ITM Prob': 'ITM Probability',
                               'OTM Prob': 'OTM Probability',
                               'Short Term~': 'Short Term Opinion Signal'},
                'logical_columns': ['Symbol',
                                    'Option Ask Price',
                                    'Bid Price',
                                    'Percent Change',
                                    'Volume',
                                    'Expiration Date',
                                    'DTE',
                                    'Strike Price',
                                    'Option Type',
                                    'Moneyness',
                                    'Option Ask Price',
                                    'Option Last Price',
                                    'Option Volume',
                                    'Total Options Open Interest',
                                    'IV Rank',
                                    'Delta',
                                    'Theta',
                                    'Vega',
                                    'Break Even (Ask)',
                                    '% to Break Even (Ask)',
                                    'Yield to Strike%',
                                    'Yield to Strike Annual Rtn%',
                                    'ITM Probability',
                                    'OTM Probability',
                                    'Short Term Opinion Signal']},
 'protective_collar': {'source_example': 'catalog/references/protective-collar-option-screener-protective-collar-etf-08-30-2025.csv',
                       'footer_timestamp': '08-30-2025 09:18pm CDT',
                       'columns': ['Symbol',
                                   'Price~',
                                   'Exp Date',
                                   'DTE',
                                   'Leg1 Strike',
                                   'Type',
                                   'Bid1',
                                   'Leg2 Strike',
                                   'Type',
                                   'Ask2',
                                   'BE',
                                   'Net Cr(Db)',
                                   '%Cost',
                                   'Max Profit',
                                   'Max Loss',
                                   'Upside',
                                   'Downside',
                                   'Delta',
                                   'Profit Prob'],
                       'sample_row': ['GLD',
                                      '318.07',
                                      '2025-10-17',
                                      '48',
                                      '335.00',
                                      'Call',
                                      '2.62',
                                      '275.00',
                                      'Put',
                                      '0.19',
                                      '315.64',
                                      '2.43',
                                      '0.8%',
                                      '19.36',
                                      '40.64',
                                      '6.09%',
                                      '-12.78%',
                                      '0.744102',
                                      '55.1%']},
 'long_call_diagonal': {'source_example': 'catalog/references/long-call-diagonal-option-screener-long-call-diagonal-08-30-2025.csv',
                        'footer_timestamp': '08-30-2025 09:26pm CDT',
                        'columns': ['Symbol',
                                    'Price~',
                                    'Exp Leg1',
                                    'Leg1 Strike',
                                    'Type',
                                    'Ask1',
                                    'Exp Leg2',
                                    'Leg2 Strike',
                                    'Type',
                                    'Bid2',
                                    'Net Debit',
                                    'Leg1 IV',
                                    'Leg2 IV',
                                    '(IV Skew)',
                                    'IV Rank',
                                    'IV/HV',
                                    'Net Delta',
                                    'Net Vega'],
                        'sample_row': ['GLD',
                                       '318.07',
                                       '2025-12-19',
                                       '300.00',
                                       'Call',
                                       '24.8',
                                       '2025-09-30',
                                       '335.00',
                                       'Call',
                                       '1.3',
                                       '23.5',
                                       '14.97%',
                                       '17.12%',
                                       '2.15%',
                                       '21.97%',
                                       '1.1750551811193',
                                       '0.644199',
                                       '0.225347']},
 'short_iron_condor': {'source_example': 'catalog/references/short-iron-condor-option-screener-short-iron-condor-08-30-2025.csv',
                       'footer_timestamp': '08-30-2025 09:29pm CDT',
                       'columns': ['Symbol',
                                   'Price~',
                                   'Exp Date',
                                   'DTE',
                                   'Leg1 Strike',
                                   'Type',
                                   'Ask1',
                                   'Leg2 Strike',
                                   'Type',
                                   'Bid2',
                                   'Leg3 Strike',
                                   'Type',
                                   'Bid3',
                                   'Leg4 Strike',
                                   'Type',
                                   'Ask4',
                                   'BE+',
                                   'BE-',
                                   'Max Profit',
                                   'Max Loss',
                                   'Risk/Reward',
                                   'IV Rank',
                                   'Loss Prob'],
                       'sample_row': ['IWM',
                                      '235.17',
                                      '2025-09-30',
                                      '31',
                                      '215.00',
                                      'Put',
                                      '0.88',
                                      '220.00',
                                      'Put',
                                      '1.35',
                                      '240.00',
                                      'Call',
                                      '3.41',
                                      '245.00',
                                      'Call',
                                      '1.93',
                                      '241.95',
                                      '218.05',
                                      '1.95',
                                      '3.05',
                                      '1.56 to 1',
                                      '7.31%',
                                      '41.5%']},
 'vertical_bear_call': {'source_example': 'catalog/references/bear-call-spread-option-screener-vertical-bear-call-etf-08-30-2025.csv',
                        'footer_timestamp': '08-30-2025 09:37pm CDT',
                        'columns': ['Symbol',
                                    'Price~',
                                    'Exp Date',
                                    'DTE',
                                    'Leg1 Strike',
                                    'Type',
                                    'Bid1',
                                    'Leg2 Strike',
                                    'Type',
                                    'Ask2',
                                    'BE',
                                    'BE%',
                                    'Max Profit',
                                    'Max Loss',
                                    'Max Profit%',
                                    'Risk/Reward',
                                    'IV Rank',
                                    'Loss Prob'],
                        'sample_row': ['GLD',
                                       '318.07',
                                       '2025-09-19',
                                       '20',
                                       '325.00',
                                       'Call',
                                       '2.41',
                                       '328.00',
                                       'Call',
                                       '2.02',
                                       '325.39',
                                       '2.30%',
                                       '0.39',
                                       '2.61',
                                       '+14.94%',
                                       '6.69 to 1',
                                       '21.97%',
                                       '28.4%']}}
